name: RocketSeat
title: Uma startup criada para educar, inspirar e conectar programadores e empreendedores.
email: oi@rocketseat.com.br
description: Cursos, eventos, conteúdo e comunidade, as ferramentas necessárias para que você possa construir coisas extraordinárias e ser o protagonista da mudança nesse cenário de tecnologia e inovação.
baseurl: ""
url: "http://rocketseat.com.br"
timezone: America/Sao_Paulo
locale: pt_BR
permalink: none

# Social
facebook_publisher: rocketseat
facebook_author: rocketseat

facebook_pixel_id: 227628427740337
google_analytics_id: UA-99997611-1

# Assets Compression
assets:
    cache: _assets/_cache
    prefix: "/assets"

    autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    assets:
        - "*.jpg"
        - "*.png"
        - "*.svg"
        - "*.ttf"
        - "*.eot"
        - "*.otf"
        - "*.woff"
        - "*.woff2"

    sources:
        - _assets
        - _assets/css
        - _assets/img
        - _assets/js
        - _assets/fonts

# Build settings
markdown: kramdown

# Pagination
paginate: 12
paginate_path: "/blog/:num/"

gems:
    - jekyll-paginate
    - jekyll-assets
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-redirect-from

exclude:
    - Gemfile
    - Gemfile.lock

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port
