name: RocketSeat
title: Tire sua ideia do papel e crie sua própria startup
email: oi@rocketseat.com.br
description: Tire sua ideia do papel e crie sua própria startup
baseurl: ""
url: "http://rocketseat.com.br"
timezone: America/Sao_Paulo
locale: pt_BR
permalink: none

# Social

facebook_publisher: rocketseat
facebook_author: rocketseat

facebook_pixel_id: 227628427740337
google_analytics_id: UA-99997611-1

# Assets Compression
assets:
    cache: _assets/_cache
    prefix: "/assets"

    autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    assets:
        - "*.png"
        - "*.svg"

    sources:
        - _assets/css
        - _assets/img
        - _assets/js
        - _assets

# Build settings
markdown: kramdown

# Pagination
paginate: 12
paginate_path: "/blog/:num/"

# Collection
collections:
    ebooks:
        output: true
        permalink: /:title.html

gems:
    - jekyll-paginate
    - jekyll-assets
    - jekyll-sitemap
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port
